name: Semgrep SAST Scanning

on:
    push:
        branches: 
            - master
    pull_request:

jobs:
    semgrep:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Python Environment
              uses: actions/checkout@v4
              with:
                python-version: '3.x'

            - name: Install Semgrep
              run: pip install semgrep
            
            - name: Run Semgrep
              run: semgrep --config auto --error || true