name: DevSecOps Security Scanning Pipeline

on:
    push:
        branches: 
            - master
    pull_request:

jobs:
    semgrep:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Python Environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Install Semgrep
              run: pip install semgrep
            
            - name: Run Semgrep SAST Scanning
              run: semgrep --config auto --json --output semgrep-report.json
            
            - name: Upload Semgrep JSON report
              uses: actions/upload-artifact@v4
              with:
                name: SAST Scan Report
                path: semgrep-report.json
            
            - name: Install Retire.js
              run: npm install -g retire

            - name: Run Retire.js SCA Scanning
              run: retire --outputformat json --outputpath retire-report.json || true

            - name: Upload Retire.js JSON report
              uses: actions/upload-artifact@v4
              with:
                name: SCA Scan Report
                path: retire-report.json  