name: DevSecOps Security Scanning Pipeline

on:
    push:
        branches: 
            - master
    pull_request:

jobs:
    SAST:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Python Environment
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'

            - name: Install Semgrep
              run: pip install semgrep
            
            - name: Run Semgrep SAST Scanning
              run: semgrep --config auto --json --output semgrep-report.json
            
            - name: Upload Semgrep JSON report
              uses: actions/upload-artifact@v4
              with:
                name: SAST Scan Report
                path: semgrep-report.json
    
    SCA:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Run npm audit and save report
              run: npm audit --json > npm-audit-report.json || true
              
            - name: Upload npm audit report
              uses: actions/upload-artifact@v4
              with:
                name: npm-audit-report
                path: npm-audit-report.json